name: Deploy on AWS

on:
  workflow_call:
    inputs:
      EB_APP:
        type: string
        required: true
      EB_ENVIRONMENT:
        type: string
        required: true
      IMAGE_PATH:
        type: string
        required: true
        default: “ghcr.io/3t-operations-team/desk-bookings-be:master”

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create Dockerrun.aws.json
        run: |
          echo "{
            \"AWSEBDockerrunVersion\": \"1\",
            \"Authentication\": {
              \"Bucket\": \"${{ vars.S3_BUCKET_NAME}}\",
              \"Key\": \"${{ vars.REGISTRY_AUTH_KEY_FILE }}\"
             },
             \"Image\": {
              \"Name\": \"${{ inputs.IMAGE_PATH }}\",
              \"Update\": \"true\"
             },
             \"Ports\": [{
                \"ContainerPort\": \"8080\",
                \"HostPort\": \"5000\"
             }]
          }" > Dockerrun.aws.json
      - name: Check dockerrun content
        run: |
          echo "$(cat Dockerrun.aws.json)"
          
      - name: Deploy to Elastic Beanstalk
        run: |
          aws s3 cp "./Dockerrun.aws.json" s3://elasticbeanstalk-us-east-1-${{ secrets.AWS_ACCOUNT_ID }}/artifact/${{ inputs.EB_APP }}/${{ inputs.EB_ENVIRONMENT }}/${{ github.run_id }}-be/
          aws elasticbeanstalk create-application-version --application-name ${{ inputs.EB_APP }} --version-label ${{github.run_id}}-be --description ${{ github.run_id }}-be --source-bundle S3Bucket="elasticbeanstalk-us-east-1-${{ secrets.AWS_ACCOUNT_ID }}",S3Key="artifact/${{ inputs.EB_APP }}/${{ inputs.EB_ENVIRONMENT }}/${{github.run_id}}-be/Dockerrun.aws.json"
          aws elasticbeanstalk update-environment --application-name ${{ inputs.EB_APP }} --environment-name ${{ inputs.EB_ENVIRONMENT }} --version-label ${{ github.run_id }}-be
          aws elasticbeanstalk wait environment-updated --application-name ${{ inputs.EB_APP }} --environment-name ${{ inputs.EB_ENVIRONMENT }}
